-- 코드를 입력하세요
SELECT BO.BOOK_ID, AU.AUTHOR_NAME, SUBSTR(BO.PUBLISHED_DATE, 1, 10) AS PUBLISHED_DATE
FROM BOOK BO
INNER JOIN AUTHOR AU ON AU.AUTHOR_ID = BO.AUTHOR_ID
WHERE BO.CATEGORY = '경제'
ORDER BY BO.PUBLISHED_DATE ASC;